
language: objective-c
osx_image: xcode9.4

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Build the framework
    - xcodebuild clean build -scheme 'libde265' -sdk macosx -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libde265-iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libde265-tvOS' -sdk appletvsimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libde265-watchOS' -sdk watchsimulator -configuration Debug | xcpretty -c

    - echo Build the example app
    - xcodebuild build -scheme 'libde265Example' -sdk macosx -configuration Debug | xcpretty -c